### ISSUE TITLE
使用MD5戳生成文件和url路径不一致

### ISSUE THREAD

**Issue by yeyeye0525** [jiangyuan/fis3-postprocessor-extras_uri#1]
您好，使用您的插件后发现生成的文件为：glob_55059dd.css
而html引用的路径为：glob_23f7957.css，
不知道是什么原因导致的，烦请解答一下，谢谢了

**Comment by jiangyuan** [comment]
不知道你的场景怎样，但推测你的配置出了问题。
这个插件只会修改类 html 的文件，其他文件一律忽略，所以也不会影响 hash 。
